# Generated by Django 5.0 on 2026-03-10

import django.core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import profiles.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID for NFC/QR scanning', unique=True)),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('Unknown', 'Unknown')], default='Unknown', max_length=5)),
                ('chronic_diseases', models.TextField(blank=True, help_text='List of chronic conditions (e.g., Diabetes, Hypertension)', verbose_name='Chronic Diseases')),
                ('allergies', models.TextField(blank=True, help_text='Known allergies', verbose_name='Allergies')),
                ('emergency_notes', models.TextField(blank=True, help_text='Critical medical notes for first responders', verbose_name='Emergency Notes')),
                ('insurance_provider', models.CharField(blank=True, max_length=200, verbose_name='Insurance Provider')),
                ('insurance_number', models.CharField(blank=True, max_length=50, verbose_name='Insurance Number')),
                ('insurance_image', models.ImageField(blank=True, null=True, upload_to='insurance/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf'])], verbose_name='Insurance Card Image')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Height (cm)')),
                ('weight', models.PositiveIntegerField(blank=True, null=True, verbose_name='Weight (kg)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medical Profile',
                'verbose_name_plural': 'Medical Profiles',
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Medication Name')),
                ('dosage', models.CharField(help_text='e.g., 500mg twice daily', max_length=100, verbose_name='Dosage')),
                ('frequency', models.CharField(blank=True, max_length=100, verbose_name='Frequency')),
                ('is_active', models.BooleanField(default=True, verbose_name='Currently Taking')),
                ('notes', models.TextField(blank=True, verbose_name='Additional Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='profiles.medicalprofile')),
            ],
            options={
                'verbose_name': 'Medication',
                'verbose_name_plural': 'Medications',
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Contact Name')),
                ('relationship', models.CharField(choices=[('spouse', 'Spouse'), ('parent', 'Parent'), ('sibling', 'Sibling'), ('child', 'Child'), ('friend', 'Friend'), ('other', 'Other')], max_length=20, verbose_name='Relationship')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('alternate_phone', models.CharField(blank=True, max_length=15, verbose_name='Alternate Phone')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Primary Contact')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='profiles.medicalprofile')),
            ],
            options={
                'verbose_name': 'Emergency Contact',
                'verbose_name_plural': 'Emergency Contacts',
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MedicalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('surgery', 'Surgery'), ('hospitalization', 'Hospitalization'), ('diagnosis', 'Diagnosis'), ('emergency', 'Emergency'), ('checkup', 'Check-up'), ('other', 'Other')], max_length=20, verbose_name='Event Type')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date', models.DateField(verbose_name='Event Date')),
                ('hospital_name', models.CharField(blank=True, max_length=200, verbose_name='Hospital/Clinic Name')),
                ('doctor_name', models.CharField(blank=True, max_length=200, verbose_name='Doctor Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_events', to='profiles.medicalprofile')),
            ],
            options={
                'verbose_name': 'Medical Event',
                'verbose_name_plural': 'Medical Events',
                'ordering': ['-date'],
            },
        ),
    ]
